# Copyright (c) 2023 CogniPilot Foundation
# SPDX-License-Identifier: Apache-2.0

manifest:

  group-filter:
    - +optional

  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: cognipilot
      url-base: https://github.com/CogniPilot

  projects:
    - name: zephyr
      remote: cognipilot
      west-commands: scripts/west-commands.yml
      revision: 54b63152053707eb21810c2e54a09905b432257f # main-with-patches 12/15/25
      import:
        - name-allowlist:
          - nanopb
          - mbedtls
          - hal_nxp
          - hal_afbr
          - cmsis
          - cmsis_6
          - cmsis-dsp
          - fatfs
          - segger
          - mcuboot
    - name: zros
      remote: cognipilot
      revision: 843348bca3a15e914914b90057369b9616302e20 # main 10/27/25
      path: modules/lib/zros
    - name: cyecca
      remote: cognipilot
      revision: 64d1f0dc5127d85765909f0c3525cc38305dac19 # main 11/17/25
      path: modules/lib/cyecca
    - name: synapse_pb
      remote: cognipilot
      revision: d14faa3fbce8ebe6412b252724ba3b47df1106c7 # main 12/16/25
      path: modules/lib/synapse_pb
    - name: hal_nxp
      remote: cognipilot
      revision: cf8f1631e862528ee044850bcc70273975b90771 # master 10/27/25
      path: modules/hal/nxp
    - name: hal_afbr
      remote: zephyrproject-rtos
      revision: 1abf6947457380934e27f92508ec5532ddedfc6d # add-blobs-for-fpu
      path: modules/hal/afbr
    - name: zros_drivers
      remote: cognipilot
      revision: fb7e9982a96c30541f60815ab8994a1fcdfb8f55 # main 12/16/25
      path: modules/lib/zros_drivers
    - name: zephyr_boards
      remote: cognipilot
      revision: 4b4d98928fb9ab4a98133b5607d619a32de6af11 # main 12/16/25
      path: modules/lib/zephyr_boards
