#!/bin/bash
set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
CYECCA_PATH=${CYECCA_ROOT:-$SCRIPT_DIR/../../modules/lib/cyecca}

# disable virtual env if running (west venv)
PYTHON_PATH=$(dirname -- "$(command -v python)")
if [ -f "$PYTHON_PATH/activate" ]; then
    source "$PYTHON_PATH/activate"
    deactivate
fi

unset PYTHONPATH
source "${CYECCA_PATH}/.venv/bin/activate"
echo python path: $PYTHONPATH
echo python3 "$(command -v python3)"

python3 "$@"

# vi: ts=4 sw=4 et
